import Head from "next/head";
import NavBar from "compontents/molecules/NavBar";
import TopHeader from "compontents/molecules/TopHeader";
import Hero from "compontents/organisms/Hero";
import OurMission from "compontents/organisms/OurMission";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sam | NGO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TopHeader />
      <NavBar />
      <Hero />
      <OurMission />
    </div>
  );
}
